spring:
  application:
    name: cybersec
#server:
  #ssl:
  #  enabled: true
  #  key-store: classpath:server-keystore.p12
  #  key-store-password: changeit
  #  key-store-type: PKCS12
  #  key-alias: server
    
    #client-auth: need
    #trust-store: classpath:client-truststore.p12
    #trust-store-password: changeit
    #trust-store-type: PKCS12

    # curl --cert client.crt --key client.key --cacert ca.crt https://localhost:8080/hello-big-content